### PR TITLE
 support unix sockets

### PR DESCRIPTION
**Pull request by sigmonsays**

### CODE REVIEW

**Comment by alphazero** [comment]
Tested?

**Comment by sigmonsays** [comment]
No unit tests were created, but I have gotten a unix socket connection
and a get/set working.

```
spec := redis.DefaultSpec()
spec.Db(0)
spec.Host("/var/run/lama/redis.sock")
spec.Port(0)
client, e := redis.NewSynchClientWithSpec(spec);
if e != nil { log.Println ("failed to create the client", e); return }


key := "examples/hello/user.name";
value, e := client.Get(key);
if e!= nil { log.Println ("error on Get", e); return }


newval := fmt.Sprintf("Some new value %d", time.Now().Unix())
fmt.Printf("Setting new value to %q\n", newval)

client.Set(key, []byte(newval))

fmt.Printf("old value is %q\n", value)
```

On Fri, May 25, 2012 at 12:20 PM, Joubin Houshyar
reply@reply.github.com
wrote:

**Comment by alphazero** [comment]
Ok, I'll need to review to make sure this is effectively isolated.  Just please do one more update on Redis version, and GOxxx details of your setup and I'll try to get to it later this weekend.  Also, since you are in a helping mood :) there are other gaps in the driver that could use patches. Heads up however that I Go-Redis is slated for a major review and possible refactoring as the code base was released a few days after Go's initial release.

**Comment by alphazero** [comment]
Thank you!

**Pull request merged**
