### PR TITLE
support latest version of go r60 (released 2011/09/07)

### PR DESCRIPTION
**Pull request by kpm**
support latest version of go r60 (released 2011/09/07)

Added goinstall instruction to readme.

Removed a debug output.

tkawachi:   Changed a response type for KEYS to MULTI_BULK
simonjefford    hopefully, this will now work with goinstall

### CODE REVIEW

**Comment by alphazero** [comment]
I need to install go on my new laptop, so the Q is: has this been tested and all is OK?

**Comment by alphazero** [comment]
I do appreciate the effort and the pull request but: 
- you need to test your mods before submitting a pull request.  Your protocol.go imports log (which you have commented out) so it doesn't compile.
- second issue with this pull request is that the directory structure has been changed by simon downstream.  It was under ~/src/pkg/redis for a specific reason and conformant to go conventions e.g. $GROOT/src/pkg/bytes.  (besides that the package is not named goredis in sources, so there are other planned packages for Go-Redis which would need to find a happy home under Go-Redis/src/pkg)  

I'll merge this on my end and will give you folks credit in the changelog but can't accept this pull.

Thank you.

**Comment by kpm** [comment]
Terribly sorry about the non-build.  I must have not used goinstall
with the -u option (update already-downloaded packages) and not
realised.

Kristian

On 22 September 2011 00:08, Joubin Houshyar
reply@reply.github.com
wrote:

**Comment by alphazero** [comment]
np, Kristian.  I appreciate the thought.

Joubin

**Pull request closed without merging**
